- name: Installer GitLab Runner
  hosts: gitlab
  become: yes
  vars:
    gitlab_url: http://172.16.228.6/
    gitlab_registration_token: RwvPwuG36ya4rugeUFTg
    runner_description: My Runner
    runner_executor: shell
  tasks:
    - name: Installer les dépendances
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      loop:
        - curl
        - apt-transport-https
    - name: Ajouter le repository de GitLab Runner
      shell: |
        curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh | sudo bash
    - name: Installer GitLab Runner
      apt:
        name: gitlab-runner
        state: latest
    - name: Enregistrer GitLab Runner
      shell: |
        gitlab-runner register --non-interactive --url "{{ gitlab_url }}" --registration-token "{{ gitlab_registration_token }}" --description "{{ runner_description }}" --executor "{{ runner_executor }}"
